version: "3"
services:
  radvent:
    build: radvent
    ports:
      - "3000:3000"
    environment:
      year: "2018"
      RAILS_ENV: "production"
    volumes:
      - ./data/:/data/
  web:
    image: nginx:1.15.6-alpine
    ports:
      - "80:80"
    volumes:
      - ./web/default.conf:/etc/nginx/conf.d/default.conf
      - ./web/.htpasswd:/etc/nginx/.htpasswd
    links:
      - radvent
